[build-system]
requires = [
    "setuptools<66",
    "setuptools_scm[toml]>=3.5.0",
]

[tool.setuptools_scm]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
known_first_party = "pudl_catalog"
