name: pre-commit-ci-auto-merge

on:
  workflow_run:
    types:
    - completed
    workflows:
    - 'tox-pytest'

jobs:
  bot-auto-merge:
    name: Auto-merge passing pre-commit-ci PRs
    runs-on: ubuntu-latest
    steps:
    - name: Auto-merge passing pre-commit-ci PRs
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      uses: ridedott/merge-me-action@v2
      with:
        GITHUB_LOGIN: pre-commit-ci
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
